### ISSUE TITLE
Stated Example in Get-Help doesn't work

### ISSUE THREAD

**Issue by webash** [jasonshave/CxdCallData#1]
Attempting to use the example as given in Get-Help give a 'Parameter set cannot be resolved' error.

![image](https://user-images.githubusercontent.com/6205899/37831528-bb0100ba-2e9d-11e8-8cf0-1fbc053c7751.png)

I'm assuming something has changed but the documentation hasn't been updated to reflect that?

**Comment by jasonshave** [comment]
Which version are you using?

**Comment by webash** [comment]
I just downloaded it from the PSGallery as of ~30 minutes ago.
![image](https://user-images.githubusercontent.com/6205899/37831841-b8beec80-2e9e-11e8-9d5b-2a5a3546b277.png)

**Comment by jasonshave** [comment]
Updated to version 1.2.3.4 and tested with your example. Uploaded to PSG as well. Thanks!
